env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://localhost:5000
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://localhost:5000
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: IGNORE
    customMessage: ''
    id: 10049
  - action: IGNORE
    customMessage: ''
    id: 10055
  - action: IGNORE
    customMessage: ''
    id: 10096
  - action: IGNORE
    customMessage: ''
    id: 10109
  - action: IGNORE
    customMessage: ''
    id: 10110
  type: outputSummary
