env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://localhost:4200
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://localhost:4200
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules:
  - action: IGNORE
    customMessage: ''
    id: 10049
  - action: IGNORE
    customMessage: ''
    id: 10055
  - action: IGNORE
    customMessage: ''
    id: 10096
  - action: IGNORE
    customMessage: ''
    id: 10109
  - action: IGNORE
    customMessage: ''
    id: 10110
  - action: IGNORE
    customMessage: ''
    id: 90034
  - action: IGNORE
    customMessage: ''
    id: 40046
  - action: IGNORE
    customMessage: ''
    id: 90035
  - action: IGNORE
    customMessage: ''
    id: 90036
  - action: IGNORE
    customMessage: ''
    id: 40015
  - action: IGNORE
    customMessage: ''
    id: 90025
  - action: IGNORE
    customMessage: ''
    id: 40040
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: reports/zap_report_baseline.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
